INTERNAL void con_initialize(TTAFont* console_font_handle, Texture console_font_atlas);
INTERNAL void con_print(const char* message);
INTERNAL void con_printf(char* fmt, ...);
INTERNAL void con_command(char* text_command);
INTERNAL void con_toggle();
INTERNAL void con_update(real32 dt);
INTERNAL void con_render(ShaderProgram ui_shader, ShaderProgram text_shader);
INTERNAL void con_keydown(SDL_KeyboardEvent& keyevent);
INTERNAL bool con_is_shown();
INTERNAL bool con_is_hidden();